export const personJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  name: 'Mostafa Gholami',
  alternateName: 'mst-ghi',
  email: 'mostafagholamidev@gmail.com',
  telephone: '+989365895522',
  birthDate: '1993-04-02',
  jobTitle: 'Senior Full-Stack Developer',
  description:
    'Senior Full-Stack Developer with 9+ years of experience designing and building scalable web platforms using NestJS, Next.js, Golang, and Turborepo. Specialized in monorepo architectures, multi-tenant systems, real-time features, and clean, maintainable codebases. Experienced in mobile development with React Native.',
  url: 'https://mst-ghi.github.io/',
  image: 'https://mst-ghi.github.io/me-square.png',
  address: {
    '@type': 'PostalAddress',
    addressLocality: 'Tehran',
    addressCountry: 'Iran',
  },
  sameAs: [
    'https://t.me/mostafa_ghi',
    'https://github.com/mst-ghi',
    'https://www.linkedin.com/in/mst-ghi/',
  ],
  knowsAbout: [
    'NestJS',
    'Node.js',
    'Golang',
    'Gin',
    'Gorm',
    'Atlas',
    'Bob',
    'OpenTelemetry',
    'TypeORM',
    'Prisma',
    'Redis',
    'Socket.IO',
    'Kafka',
    'JWT',
    'ACL',
    'Microservices',
    'Monorepo',
    'Turborepo',
    'Next.js',
    'React.js',
    'React Native',
    'Vite',
    'React Query',
    'Zustand',
    'Mantine UI',
    'Material UI',
    'Tailwind CSS',
    'PWA',
    'Docker',
    'Swagger',
    'Caching',
    'Queue',
    'Multitenant projects',
    'Socket programming',
  ],
  hasOccupation: {
    '@type': 'Occupation',
    name: 'Software Developer',
    occupationalCategory: 'Software Development',
  },
};

export const websiteJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'Mostafa Gholami Portfolio',
  url: 'https://mst-ghi.github.io/',
  description:
    'Portfolio and projects of Mostafa Gholami, Senior Full-Stack Developer with 9+ years of experience.',
  author: {
    '@type': 'Person',
    name: 'Mostafa Gholami',
  },
};
